version: '3.8'

services:
  api:
    container_name: ready-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ready_db
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_SECRET=your_refresh_secret
      - JWT_REFRESH_EXPIRES_IN=30d
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ready-network
    restart: unless-stopped

  postgres:
    container_name: ready-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ready_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ready-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ready-network:
    driver: bridge
